
mariadb:
  docker:
    remote_repo: mariadb
  docker_run:
    opts: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'
    var: $devkit_root/var/mariadb
    listen:
      - 127.0.0.1:3306
