
mariadb:
  docker:
    remote_repo: mariadb
  docker_run:
    opts: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'
    var: $devkit_root/var/mariadb
    listen:
      - 127.0.0.1:3306

postgres:
  docker:
    remote_repo: postgres
  docker_run:
    opts: ''
    var: $devkit_root/var/postgres
    listen:
      - 127.0.0.1:5432

nginx:
  docker:
    remote_repo: nginx
  docker_run:
    opts: ''
    var: $devkit_root/var/nginx
    listen:
      - 127.0.0.1:80
